# Generated by Django 3.2.13 on 2022-08-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('techName', models.CharField(max_length=200)),
                ('techSubname', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Technology',
            },
        ),
    ]
