# Generated by Django 3.2.13 on 2022-08-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AddField(
            model_name='technology',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
