# Generated by Django 3.2.13 on 2022-08-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220808_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='title',
        ),
        migrations.AlterField(
            model_name='technology',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
