# Generated by Django 3.2.13 on 2022-08-09 17:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_technology_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
