# Generated by Django 3.2.13 on 2022-08-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_technology_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=500)),
                ('initial_date', models.DateTimeField()),
                ('technology', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.technology')),
            ],
        ),
    ]
