# Generated by Django 3.2.13 on 2022-08-10 17:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='initial_date',
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
