# Generated by Django 3.2.13 on 2022-08-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220810_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='experience',
            field=models.CharField(choices=[{'a', 'A'}, {'b', 'B'}, {'C', 'c'}], max_length=300, null=True),
        ),
    ]
