# Generated by Django 3.2.13 on 2022-08-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_questions_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='experience',
            field=models.CharField(choices=[{'fresher', 'Fresher'}, {'Intermediate', 'intermediate'}, {'professional', 'Professional'}], max_length=300, null=True),
        ),
        migrations.AlterModelTable(
            name='questions',
            table='Questions',
        ),
    ]
